/* 2026 AI Agent 横评 · 三语数据 (zh / en / ja) */
const DIM_KEYS = ["code", "reasoning", "multimodal", "agent", "chinese", "price"];

const I18N = {
zh: {
  ui: {
    doc_title: "2026 AI Agent 横评 | 十大智能体优劣全对比",
    meta_desc: "2026 年十大 AI Agent 横向评测：Claude、ChatGPT、Gemini、Grok、Copilot、DeepSeek、Qwen、Kimi、GLM、Manus 的优劣势、价格与选购指南。",
    logo: "🤖 Agent 横评 2026",
    nav_agents: "十家详解", nav_compare: "对比表", nav_guide: "选购指南", nav_notes: "说明",
    kicker: "2026 · 十月更新",
    hero_a: "2026 年十大 AI Agent", hero_b: "横向评测",
    hero_sub: "Claude · ChatGPT · Gemini · Grok · Copilot · DeepSeek · Qwen · Kimi · GLM · Manus<br>代码、推理、多模态、Agent 自主性、中文、价格 —— 六个维度，一次讲透。",
    stat_n1: "10", stat_l1: "家主流 Agent",
    stat_n2: "6", stat_l2: "个评测维度",
    stat_n3: "4", stat_l3: "家大陆可用国产",
    cta: "开始看评测 ↓",
    tldr_title: "一句话结论", tldr_tag: "TL;DR",
    tldr: [
      { t: "🏆 综合最强", p: "Claude（代码/Agent）与 GPT-6（生态）并列第一梯队，程序员闭眼入。" },
      { t: "💰 性价比之王", p: "DeepSeek：API 价格是国外旗舰的 1/10–1/30，中文推理顶级。" },
      { t: "🇨🇳 国产之光", p: "GLM：开源编程/Agent 双 SOTA，744B 真开源，体感逼近 Claude。" },
      { t: "🔓 开源天花板", p: "Kimi K3：2.8T 史上最大开源权重；Qwen：单卡可跑的私有化首选。" },
    ],
    agents_title: "十家详解",
    agents_desc: "点击卡片展开优劣势。🇨🇳 表示中国大陆可直接使用。",
    filters: { all: "全部", china: "🇨🇳 大陆可用", code: "💻 代码强", price: "💰 性价比高", agent: "🤖 Agent 自主性强" },
    compare_title: "六维能力对比",
    compare_desc: "★★★★★ 为第一梯队。星级为基于公开基准与媒体横评的综合判断，非精确测量。",
    price_title: "订阅价格一览",
    price_headers: ["产品", "免费档", "入门付费", "主力档", "顶级档"],
    guide_title: "选购指南",
    notes_title: "说明与数据来源",
    notes: [
      "本页内容整理自 2026 年 10 月的公开资料检索（模型官网、科技媒体、基准榜单），价格与版本变动较快，<b>下单前请以各官网为准复核</b>。",
      "“中文支持”评分综合了语言质量与中国大陆可用性：Claude / ChatGPT / Gemini / Grok 在大陆均无官方服务，Copilot 国际版在大陆基本不可用。",
      "开源 Agent 框架同样值得关注：<b>LangGraph</b>（状态图编排，月下载数千万）、<b>CrewAI</b>（角色式多智能体）、<b>OpenHands</b>（自主编程 Agent），以及各大厂官方 SDK（Agent Framework / Agents SDK / ADK）。",
    ],
    notes_update: "最后更新：2026-10-05 · 纯静态页面，无后端，可自由转载（请注明出处）。",
    footer: "🤖 2026 AI Agent 横评 · 由 AI 助手自动生成与部署 · 部署于 GitHub Pages",
    dims: { code: "代码能力", reasoning: "推理", multimodal: "多模态", agent: "Agent 自主性", chinese: "中文支持", price: "价格亲和" },
    pros_label: "✅ 优势", cons_label: "❌ 劣势", verdict_label: "一句话点评：",
    models_label: "旗舰模型", context_label: "上下文", price_label: "价格",
    lang_label: "语言",
  },
  guides: [
    { title: "程序员 / 重度编码", body: "Claude（Code 生态最强）或 GPT-6 Sol；国产认准 GLM（开源 Coding SOTA，Coding Plan 省心）；预算敏感选 DeepSeek/Kimi API。" },
    { title: "中文写作 / 学习 / 日常问答（国内）", body: "智谱清言（GLM，免费）、Kimi（长文档）、DeepSeek（深度推理）。" },
    { title: "办公全家桶", body: "企业看 Microsoft 365 Copilot；国内个人可看 WPS AI。" },
    { title: "自主 Agent 玩家", body: "Manus（最自主但有信任风险）、Claude Cowork、ChatGPT Work，或用 OpenHands 自建。" },
    { title: "开发者自建 / 私有化", body: "Qwen3.8-27B（单卡可跑）、DeepSeek V4.1（MIT）、Kimi K3（最强但需集群）。" },
  ],
  agents: [
    {
      id: "claude", name: "Claude", company: "Anthropic",
      tagline: "代码与长任务 Agent 的长期王者",
      models: ["Opus 5.5（旗舰编码/推理）", "Fable 5.1（最强通用/长时 Agent）", "Sonnet 5.5（均衡主力）"],
      context: "100 万 tokens", price: "Free / Pro $20/月 / Max $100–$200/月",
      tiers: ["✅（Sonnet 级）", "—", "Pro $20/月", "Max $100/$200/月"],
      china: false, chinaNote: "大陆无官方服务",
      scores: { code: 5, reasoning: 5, multimodal: 4, agent: 5, chinese: 4, price: 3 },
      pros: ["代码与 Agent 任务长期第一梯队：Terminal-Bench 2.1 达 80.4%，AA 智能指数 58 领先", "长上下文理解质量最好，适合大代码库与长文档", "免费档默认给 Sonnet 级别模型，免费层相对慷慨", "Claude Code / Cowork 终端与办公 Agent 生态成熟"],
      cons: ["定价贵：Opus 5.5 API $4/$20，Fable 5.1 高达 $10/$50 每百万 token", "中国大陆无官方服务", "中文网络语境、成语典故等本地化知识弱于国产模型"],
      verdict: "程序员首选，重度编码与复杂 Agent 任务的天花板；国内用户需自行解决访问问题。",
    },
    {
      id: "chatgpt", name: "ChatGPT", company: "OpenAI",
      tagline: "生态最完整的全能选手",
      models: ["GPT-6 Astra（旗舰）", "GPT-6 Sol（中端主力）", "GPT-6 Luna（轻量）", "GPT-6.1 Sol（升级版）"],
      context: "100 万 tokens", price: "Free / Go $8/月 / Plus $20/月 / Pro $200/月",
      tiers: ["✅（限量+广告）", "Go $8/月", "Plus $20/月", "Pro $200/月"],
      china: false, chinaNote: "大陆被屏蔽，无官方服务",
      scores: { code: 5, reasoning: 5, multimodal: 4, agent: 4, chinese: 4, price: 3 },
      pros: ["综合实力最强之一：GPT-6 Astra 编码实测满分档", "生态最完整：Codex 编程 Agent、Work 文档生成、语音、Deep Research", "分层定价清晰，Plus $20/月可用 Sol 级别"],
      cons: ["旗舰贵：Astra API $10/$50，Pro 档 $200/月", "免费档含广告且限制严格；Sora 独立应用已下线", "中文表达偏翻译腔，古文与网络热梗理解不如国产", "中国大陆无官方服务"],
      verdict: "全能水桶机，生态与易用性最佳；追求极致编码可选 Sol，日常用 Plus 足够。",
    },
    {
      id: "gemini", name: "Gemini", company: "Google",
      tagline: "多模态与语音的性价比之王",
      models: ["Gemini 3.8 Flash（开发者主力）", "Gemini 3.8 Live（实时语音 Agent）", "Gemini 3.1 Pro（消费旗舰）"],
      context: "100 万+ tokens", price: "Free（10/9 后仅 Flash-Lite）/ Plus $4.99/月 / Pro $19.99/月 / Ultra $99.99+/月",
      tiers: ["✅（10/9 后仅 Flash-Lite）", "Plus $4.99/月", "Pro $19.99/月", "Ultra $99.99/$199.99/月"],
      china: false, chinaNote: "大陆被屏蔽，无官方服务",
      scores: { code: 4, reasoning: 4, multimodal: 5, agent: 4, chinese: 4, price: 4 },
      pros: ["原生多模态最强：文本/图像/视频/音频/PDF 全支持", "语音实时对话领先，支持 97 种语言", "Flash 系列便宜又快，谷歌生态（搜索/安卓/Workspace）整合最深"],
      cons: ["2026-10-09 起免费档大幅缩水，只剩 Flash-Lite", "旗舰命名混乱，消费端档位对应不透明", "独立基准整体略逊 Claude/GPT-6 旗舰", "中国大陆无官方服务"],
      verdict: "多模态与语音场景首选，安卓/谷歌全家桶用户闭眼入；免费党注意 10 月后的缩水。",
    },
    {
      id: "grok", name: "Grok", company: "xAI",
      tagline: "实时信息流的叛逆者",
      models: ["Grok 4.7（旗舰）", "Grok 4.7 Fast（2 倍速）"],
      context: "50 万 tokens", price: "免费基础版 / X Premium $8–$40 / SuperGrok $10–$300/月",
      tiers: ["✅ 基础版", "X Premium $8 / Lite $10", "SuperGrok $30 / Premium+ $40", "Plus $100 / Heavy $300"],
      china: false, chinaNote: "大陆不可用（X 被屏蔽）",
      scores: { code: 4, reasoning: 4, multimodal: 4, agent: 3, chinese: 3, price: 4 },
      pros: ["X 平台实时信息搜索，时效性最强", "Grok Imagine 视频/图像生成（1080p）", "API 便宜（$2/$6），企业落地快", "调性敢说，吸引年轻用户"],
      cons: ["性能仍落后第一梯队一个身位，自报基准与第三方有差距", "订阅体系混乱：X Premium 与 SuperGrok 双店并行，模型映射不透明", "中文质量明显弱于国产模型", "中国大陆不可用"],
      verdict: "追实时热点、玩视频生成可以一试；严肃生产力任务先看前三家。",
    },
    {
      id: "copilot", name: "Microsoft Copilot", company: "微软",
      tagline: "办公场景的默认答案",
      models: ["底层混用 OpenAI Astra 与 Anthropic Fable", "Home / Code / Autopilot 三标签（2026-09 改版）"],
      context: "依底层模型而定", price: "基础免费 / M365 商业版 $21/月 / 企业版 $30/用户/月 + 按量",
      tiers: ["✅（Win/Edge 基础）", "—", "M365 商业版 $21/月", "企业版 $30/月 + 按量"],
      china: false, chinaNote: "国际版大陆基本不可用",
      scores: { code: 4, reasoning: 4, multimodal: 3, agent: 4, chinese: 3, price: 2 },
      pros: ["M365 全家桶深度集成：Word/Excel/PPT 内直接生成编辑", "Autopilot 后台持续运行的自主 Agent", "Windows/Edge 预装，触达最广"],
      cons: ["订阅 + 按量双重计费，Agent 重负载另收费，账单不可预测", "无自研旗舰基座模型，前沿模型上线慢于原生应用", "中文语感与知识本地化弱于国产助手"],
      verdict: "企业办公刚需，个人用户为 Office 整合买单；重度 Agent 用量前先算好账。",
    },
    {
      id: "deepseek", name: "DeepSeek", company: "深度求索",
      tagline: "性价比之王，开源推理之光",
      models: ["DeepSeek V4.1 Flash（原生多模态 MoE，MIT 开源）", "DeepSeek V4 Pro（1.6T，权重开源）"],
      context: "100 万 tokens", price: "App/网页免费；API 约 ¥2/¥8 每百万 token（闲时半价）",
      tiers: ["✅", "—", "API 极便宜（¥2/¥8）", "—"],
      china: true, chinaNote: "大陆完全可用",
      scores: { code: 5, reasoning: 5, multimodal: 3, agent: 4, chinese: 5, price: 5 },
      pros: ["性价比之王：API 价格是国外旗舰的 1/10–1/30，缓存命中近乎免费", "MIT 开源权重，可私有化部署", "中文推理/写作/代码注释均为第一梯队", "首发即获国产芯片零日适配，生态响应快"],
      cons: ["高峰期服务稳定性偶有波动", "视频生成等多模态弱于字节/谷歌", "敏感话题受合规审查", "C 端产品打磨弱于互联网大厂"],
      verdict: "开发者与预算敏感用户的默认选择；API 性价比无敌，日常问答免费够用。",
    },
    {
      id: "qwen", name: "Qwen", company: "阿里",
      tagline: "开源生态的绝对王者",
      models: ["Qwen3.8-Max（闭源旗舰，国产第一）", "Qwen3.8-2.4T-A95B（开源 MoE）", "Qwen3.8-27B（Apache 2.0，单卡可跑）"],
      context: "100 万 tokens（27B 经 YaRN 扩展）", price: "开源权重免费；通义 App 免费；API 按量便宜",
      tiers: ["✅", "—", "API 便宜", "—"],
      china: true, chinaNote: "大陆完全可用",
      scores: { code: 4, reasoning: 4, multimodal: 4, agent: 4, chinese: 5, price: 5 },
      pros: ["开源生态最强：460+ 模型、30 亿+ 下载、30 万+ 衍生", "27B Apache 2.0 单张 RTX 4090 可跑，私有化门槛最低", "中文能力顶级，阿里云/支付宝生态整合深", "有望接入国行 Apple Intelligence"],
      cons: ["最强 Max 版闭源，2.4T 版超大规模商用需授权", "独立第三方评测证据弱于 DeepSeek", "国际开发者生态仍在追赶"],
      verdict: "想本地跑/私有化部署闭眼选 Qwen；开源 Agent 底座的事实标准。",
    },
    {
      id: "kimi", name: "Kimi", company: "月之暗面",
      tagline: "最强开源模型，长文档之王",
      models: ["Kimi K3（2.8T MoE，史上最大开源权重）", "Kimi K2.8 Preview（中端）"],
      context: "100 万 tokens（全档）", price: "App/网页免费；API K3 约 $3/$15 每百万 token",
      tiers: ["✅", "—", "API $3/$15（K3）", "—"],
      china: true, chinaNote: "大陆完全可用",
      scores: { code: 5, reasoning: 5, multimodal: 3, agent: 4, chinese: 5, price: 4 },
      pros: ["AA 智能指数 57.1，最强开源模型（全球第四）", "首个前端编码基准超越 Claude/GPT 的开源模型", "长上下文与 Agent 任务口碑好，Kimi Code 终端 Agent 好用", "中文任务优秀，大陆完全可用"],
      cons: ["权重 1.56TB，个人无法本地运行", "自研 License，商用需细读条款", "视频/语音等多模态生成弱于字节", "公司体量小于 BAT，长期投入待观察"],
      verdict: "长文档处理与开源 Agent 首选；读论文、啃代码库、大海捞针找它。",
    },
    {
      id: "glm", name: "GLM", company: "智谱AI",
      tagline: "开源 Coding / Agent 双料 SOTA",
      models: ["GLM-5（旗舰，744B 开源）", "GLM-5.3（最新，1M 上下文）", "GLM-5.3-Flash（极速便宜版）"],
      context: "1M tokens（GLM-5.3）", price: "智谱清言免费；API ¥8/¥28（5.3）；Coding Plan ¥118 起",
      tiers: ["✅（智谱清言）", "Coding Plan ¥118", "API ¥8/¥28（5.3）", "Flash ¥0.4/¥1.4"],
      china: true, chinaNote: "大陆完全可用",
      scores: { code: 5, reasoning: 5, multimodal: 4, agent: 5, chinese: 5, price: 5 },
      pros: ["编程开源 SOTA：SWE-bench-Verified 77.8、Terminal-Bench 2.0 56.2，体感逼近 Claude Opus 4.5", "Agent 开源 SOTA：BrowseComp、MCP-Atlas、τ²-Bench 均列开源第一", "真开源旗舰（744B MoE），可私有化部署；国产芯片全适配", "API 便宜：GLM-5.3 ¥8/¥28，Flash 版低至 ¥0.4/¥1.4", "GLM Coding Plan 跑通编程付费场景，2026 年港股上市募资超 700 亿港元"],
      cons: ["C 端 App（智谱清言）声量不如豆包等国民级应用", "视频生成等多模态能力弱于字节/谷歌", "内容受国内合规审查", "2026 年 2 月 Coding Plan 涨价 30% 起，涨价趋势值得关注"],
      verdict: "程序员与 Agent 重度用户的国产首选：开源、便宜、能打；写代码直接上 Coding Plan。",
    },
    {
      id: "manus", name: "Manus", company: "Butterfly Effect",
      tagline: "最自主的通用 Agent（历经风波）",
      models: ["Manus 1.6 家族（Lite / Standard / Max）"],
      context: "依任务而定（多 Agent 编排）", price: "无公开免费档；$20/月（4000 点）起",
      tiers: ["❌ 无公开免费档", "$20/月（4000 点）", "$40/月", "按量加购"],
      china: true, chinaNote: "全球可用（含中国访问），主体已迁新加坡",
      scores: { code: 4, reasoning: 4, multimodal: 4, agent: 5, chinese: 4, price: 2 },
      pros: ["Agent 自主性标杆：给目标就自主规划执行，交付成品", "GAIA 基准曾达 SOTA，多端覆盖（Web/桌面/IM/邮件委托）", "开放网络任务的端到端执行能力强"],
      cons: ["Meta 收购被叫停、恢复独立时删除用户数据，信任受重创", "信用点计费不透明，复杂任务失败率不稳定", "无持久记忆与团队协作空间", "无免费档，$20/月起偏贵"],
      verdict: "想体验“真·自主 Agent”可以一试，但先想清楚数据信任问题；生产环境建议观望。",
    },
  ],
},
en: {
  ui: {
    doc_title: "2026 AI Agent Showdown | Top 10 Compared",
    meta_desc: "2026's top 10 AI agents compared: strengths, weaknesses, pricing and buying guide for Claude, ChatGPT, Gemini, Grok, Copilot, DeepSeek, Qwen, Kimi, GLM and Manus.",
    logo: "🤖 Agent Showdown 2026",
    nav_agents: "Deep Dives", nav_compare: "Compare", nav_guide: "Buying Guide", nav_notes: "Notes",
    kicker: "2026 · October Update",
    hero_a: "2026's Top 10 AI Agents", hero_b: "Head-to-Head",
    hero_sub: "Claude · ChatGPT · Gemini · Grok · Copilot · DeepSeek · Qwen · Kimi · GLM · Manus<br>Coding, reasoning, multimodal, agent autonomy, Chinese, pricing — six dimensions, one page.",
    stat_n1: "10", stat_l1: "Top Agents",
    stat_n2: "6", stat_l2: "Dimensions",
    stat_n3: "4", stat_l3: "Available in China",
    cta: "See the reviews ↓",
    tldr_title: "Bottom Line", tldr_tag: "TL;DR",
    tldr: [
      { t: "🏆 Best Overall", p: "Claude (coding/agents) and GPT-6 (ecosystem) share the top tier — a safe pick for developers." },
      { t: "💰 Best Value", p: "DeepSeek: API costs 1/10–1/30 of Western flagships, with top-tier Chinese reasoning." },
      { t: "🇨🇳 China's Finest", p: "GLM: open-source SOTA in coding & agents, a real 744B open model that feels close to Claude." },
      { t: "🔓 Open-Source King", p: "Kimi K3: the largest open weights ever (2.8T); Qwen: the go-to for single-GPU self-hosting." },
    ],
    agents_title: "Deep Dives",
    agents_desc: "Click a card to expand strengths & weaknesses. 🇨🇳 means directly available in mainland China.",
    filters: { all: "All", china: "🇨🇳 China OK", code: "💻 Strong coding", price: "💰 Great value", agent: "🤖 Autonomous" },
    compare_title: "Six-Dimension Comparison",
    compare_desc: "★★★★★ is top tier. Ratings are a synthesis of public benchmarks and media reviews, not precise measurements.",
    price_title: "Subscription Pricing",
    price_headers: ["Product", "Free Tier", "Entry", "Main", "Top"],
    guide_title: "Buying Guide",
    notes_title: "Notes & Sources",
    notes: [
      "Compiled from public sources in October 2026 (official sites, tech media, benchmark leaderboards). Prices and model versions change fast — <b>verify on official sites before paying</b>.",
      "The “Chinese support” score blends language quality with mainland-China availability: Claude, ChatGPT, Gemini and Grok have no official service in China; Copilot's international version is largely unavailable there.",
      "Open-source agent frameworks worth watching: <b>LangGraph</b> (stateful orchestration, tens of millions of monthly downloads), <b>CrewAI</b> (role-based multi-agent), <b>OpenHands</b> (autonomous coding agent), plus official SDKs (Agent Framework / Agents SDK / ADK).",
    ],
    notes_update: "Last updated: 2026-10-05 · Pure static page, no backend. Free to share with credit.",
    footer: "🤖 2026 AI Agent Showdown · Auto-generated & deployed by an AI assistant · Hosted on GitHub Pages",
    dims: { code: "Coding", reasoning: "Reasoning", multimodal: "Multimodal", agent: "Agent Autonomy", chinese: "Chinese Support", price: "Affordability" },
    pros_label: "✅ Strengths", cons_label: "❌ Weaknesses", verdict_label: "Verdict: ",
    models_label: "Flagship Models", context_label: "Context", price_label: "Pricing",
    lang_label: "Language",
  },
  guides: [
    { title: "Developers / Heavy Coding", body: "Claude (best Code ecosystem) or GPT-6 Sol; in China go GLM (open-source coding SOTA, Coding Plan is hassle-free); on a budget, DeepSeek/Kimi APIs." },
    { title: "Chinese Writing / Study / Daily Q&A (in China)", body: "Zhipu Qingyan (GLM, free), Kimi (long docs), DeepSeek (deep reasoning)." },
    { title: "Office Suite", body: "Microsoft 365 Copilot for enterprises; WPS AI for individuals in China." },
    { title: "Autonomous Agent Enthusiasts", body: "Manus (most autonomous but trust concerns), Claude Cowork, ChatGPT Work, or self-host OpenHands." },
    { title: "Self-Hosting / Private Deploy", body: "Qwen3.8-27B (single GPU), DeepSeek V4.1 (MIT), Kimi K3 (strongest but needs a cluster)." },
  ],
  agents: [
    {
      id: "claude", name: "Claude", company: "Anthropic",
      tagline: "The long-time king of coding & long-horizon agents",
      models: ["Opus 5.5 (flagship coding/reasoning)", "Fable 5.1 (best general / long agents)", "Sonnet 5.5 (balanced workhorse)"],
      context: "1M tokens", price: "Free / Pro $20/mo / Max $100–$200/mo",
      tiers: ["✅ (Sonnet-class)", "—", "Pro $20/mo", "Max $100/$200/mo"],
      china: false, chinaNote: "No official service in China",
      scores: { code: 5, reasoning: 5, multimodal: 4, agent: 5, chinese: 4, price: 3 },
      pros: ["Top tier for coding & agents: 80.4% on Terminal-Bench 2.1, AA intelligence index 58", "Best long-context comprehension — ideal for large codebases and long docs", "Free tier ships Sonnet-class models, generous by comparison", "Mature Claude Code / Cowork agent ecosystem"],
      cons: ["Pricey: Opus 5.5 API at $4/$20, Fable 5.1 up to $10/$50 per 1M tokens", "No official service in mainland China", "Weaker than Chinese models on local internet slang, idioms and cultural context"],
      verdict: "The default for programmers — the ceiling for heavy coding and complex agent work. Users in China need their own access solution.",
    },
    {
      id: "chatgpt", name: "ChatGPT", company: "OpenAI",
      tagline: "The most complete all-rounder ecosystem",
      models: ["GPT-6 Astra (flagship)", "GPT-6 Sol (mid-tier workhorse)", "GPT-6 Luna (lightweight)", "GPT-6.1 Sol (upgraded)"],
      context: "1M tokens", price: "Free / Go $8/mo / Plus $20/mo / Pro $200/mo",
      tiers: ["✅ (limited + ads)", "Go $8/mo", "Plus $20/mo", "Pro $200/mo"],
      china: false, chinaNote: "Blocked in China, no official service",
      scores: { code: 5, reasoning: 5, multimodal: 4, agent: 4, chinese: 4, price: 3 },
      pros: ["Among the strongest overall: GPT-6 Astra aced coding evals", "Richest ecosystem: Codex coding agent, Work doc generation, voice, Deep Research", "Clear tiering — Plus $20/mo gets Sol-class models"],
      cons: ["Flagship is expensive: Astra API $10/$50, Pro tier $200/mo", "Free tier has ads and tight limits; standalone Sora app discontinued", "Chinese output can feel translated; weaker on classical Chinese and memes", "No official service in mainland China"],
      verdict: "The all-round workhorse with the best ecosystem. Sol for peak coding, Plus is plenty for daily use.",
    },
    {
      id: "gemini", name: "Gemini", company: "Google",
      tagline: "The value king of multimodal & voice",
      models: ["Gemini 3.8 Flash (developer workhorse)", "Gemini 3.8 Live (real-time voice agent)", "Gemini 3.1 Pro (consumer flagship)"],
      context: "1M+ tokens", price: "Free (Flash-Lite only after 10/9) / Plus $4.99/mo / Pro $19.99/mo / Ultra $99.99+/mo",
      tiers: ["✅ (Flash-Lite only after 10/9)", "Plus $4.99/mo", "Pro $19.99/mo", "Ultra $99.99/$199.99/mo"],
      china: false, chinaNote: "Blocked in China, no official service",
      scores: { code: 4, reasoning: 4, multimodal: 5, agent: 4, chinese: 4, price: 4 },
      pros: ["Strongest native multimodal: text/image/video/audio/PDF", "Leading real-time voice, 97 languages", "Flash line is cheap and fast; deepest Google ecosystem integration (Search/Android/Workspace)"],
      cons: ["Free tier gutted after 2026-10-09 — Flash-Lite only", "Confusing flagship naming, opaque consumer tiers", "Slightly behind Claude/GPT-6 flagships on independent benchmarks", "No official service in mainland China"],
      verdict: "Top pick for multimodal and voice; a no-brainer for Android/Google households. Free users beware the October cut.",
    },
    {
      id: "grok", name: "Grok", company: "xAI",
      tagline: "The rebellious real-time feed",
      models: ["Grok 4.7 (flagship)", "Grok 4.7 Fast (2x speed)"],
      context: "500K tokens", price: "Free basic / X Premium $8–$40 / SuperGrok $10–$300/mo",
      tiers: ["✅ Basic", "X Premium $8 / Lite $10", "SuperGrok $30 / Premium+ $40", "Plus $100 / Heavy $300"],
      china: false, chinaNote: "Unavailable in China (X is blocked)",
      scores: { code: 4, reasoning: 4, multimodal: 4, agent: 3, chinese: 3, price: 4 },
      pros: ["Real-time X search — unmatched freshness", "Grok Imagine video/image generation (1080p)", "Cheap API ($2/$6), fast enterprise adoption", "Bold tone that resonates with younger users"],
      cons: ["Still a step behind the top tier; self-reported benchmarks exceed third-party ones", "Messy subscriptions: X Premium vs SuperGrok in parallel, opaque model mapping", "Chinese quality clearly behind Chinese models", "Unavailable in mainland China"],
      verdict: "Fun for real-time trends and video generation; look at the top three for serious productivity.",
    },
    {
      id: "copilot", name: "Microsoft Copilot", company: "Microsoft",
      tagline: "The default answer for office work",
      models: ["Mix of OpenAI Astra & Anthropic Fable under the hood", "Home / Code / Autopilot tabs (Sep 2026 revamp)"],
      context: "Depends on underlying model", price: "Free basic / M365 Business $21/mo / Enterprise $30/user/mo + usage",
      tiers: ["✅ (Win/Edge basic)", "—", "M365 Business $21/mo", "Enterprise $30/mo + metered"],
      china: false, chinaNote: "International version largely unavailable in China",
      scores: { code: 4, reasoning: 4, multimodal: 3, agent: 4, chinese: 3, price: 2 },
      pros: ["Deepest M365 integration: generate/edit Word/Excel/PPT inline", "Autopilot — background autonomous agents", "Preinstalled on Windows/Edge, widest reach"],
      cons: ["Subscription + metered double billing; heavy agent use costs extra, bills unpredictable", "No in-house flagship base model; slower to ship frontier models", "Chinese tone and localization weaker than Chinese assistants"],
      verdict: "A must for enterprise office work; individuals pay for the Office integration. Budget agent-heavy usage carefully.",
    },
    {
      id: "deepseek", name: "DeepSeek", company: "DeepSeek",
      tagline: "The value king, open-source reasoning star",
      models: ["DeepSeek V4.1 Flash (native multimodal MoE, MIT open)", "DeepSeek V4 Pro (1.6T, open weights)"],
      context: "1M tokens", price: "Free app/web; API ~¥2/¥8 per 1M tokens (half off-peak)",
      tiers: ["✅", "—", "Dirt-cheap API (¥2/¥8)", "—"],
      china: true, chinaNote: "Fully available in China",
      scores: { code: 5, reasoning: 5, multimodal: 3, agent: 4, chinese: 5, price: 5 },
      pros: ["Unbeatable value: 1/10–1/30 the price of Western flagships, near-free cache hits", "MIT-open weights, self-hostable", "Top-tier Chinese reasoning, writing and code comments", "Day-zero support on domestic chips, fast ecosystem response"],
      cons: ["Occasional instability at peak hours", "Video generation and multimodal behind ByteDance/Google", "Sensitive topics filtered for compliance", "Consumer app polish behind big-tech rivals"],
      verdict: "The default for developers and the budget-conscious; unbeatable API pricing, free tier covers daily Q&A.",
    },
    {
      id: "qwen", name: "Qwen", company: "Alibaba",
      tagline: "The undisputed open-source ecosystem king",
      models: ["Qwen3.8-Max (closed flagship, China's best)", "Qwen3.8-2.4T-A95B (open MoE)", "Qwen3.8-27B (Apache 2.0, single-GPU)"],
      context: "1M tokens (27B via YaRN)", price: "Free open weights; free Tongyi app; cheap pay-as-you-go API",
      tiers: ["✅", "—", "Cheap API", "—"],
      china: true, chinaNote: "Fully available in China",
      scores: { code: 4, reasoning: 4, multimodal: 4, agent: 4, chinese: 5, price: 5 },
      pros: ["Strongest open ecosystem: 460+ models, 3B+ downloads, 300K+ derivatives", "27B Apache 2.0 runs on a single RTX 4090 — lowest self-host bar", "Top-tier Chinese, deep Alibaba Cloud/Alipay integration", "Rumored for China's Apple Intelligence"],
      cons: ["Best Max version is closed; 2.4T needs a license at huge commercial scale", "Thinner independent benchmark evidence than DeepSeek", "International dev mindshare still catching up"],
      verdict: "The blind pick for local/self-hosted deployment; the de facto open agent base model.",
    },
    {
      id: "kimi", name: "Kimi", company: "Moonshot AI",
      tagline: "Strongest open model, king of long documents",
      models: ["Kimi K3 (2.8T MoE, largest open weights ever)", "Kimi K2.8 Preview (mid-tier)"],
      context: "1M tokens (all tiers)", price: "Free app/web; K3 API ~$3/$15 per 1M tokens",
      tiers: ["✅", "—", "API $3/$15 (K3)", "—"],
      china: true, chinaNote: "Fully available in China",
      scores: { code: 5, reasoning: 5, multimodal: 3, agent: 4, chinese: 5, price: 4 },
      pros: ["AA intelligence index 57.1 — strongest open model, 4th worldwide", "First open model to beat Claude/GPT on front-end coding", "Great long-context & agent reputation; handy Kimi Code terminal agent", "Excellent Chinese, fully available in China"],
      cons: ["1.56TB weights — impossible to self-host for individuals", "Custom license, read the terms for commercial use", "Video/voice generation behind ByteDance", "Smaller company than BAT; long-term investment TBD"],
      verdict: "Top pick for long documents and open agents; reach for it for papers, codebases and needle-in-haystack search.",
    },
    {
      id: "glm", name: "GLM", company: "Zhipu AI",
      tagline: "Open-source SOTA in both coding & agents",
      models: ["GLM-5 (flagship, 744B open)", "GLM-5.3 (latest, 1M context)", "GLM-5.3-Flash (fast & cheap)"],
      context: "1M tokens (GLM-5.3)", price: "Free Qingyan app; API ¥8/¥28 (5.3); Coding Plan from ¥118",
      tiers: ["✅ (Qingyan app)", "Coding Plan ¥118", "API ¥8/¥28 (5.3)", "Flash ¥0.4/¥1.4"],
      china: true, chinaNote: "Fully available in China",
      scores: { code: 5, reasoning: 5, multimodal: 4, agent: 5, chinese: 5, price: 5 },
      pros: ["Open-source coding SOTA: 77.8 SWE-bench-Verified, 56.2 Terminal-Bench 2.0 — feels close to Claude Opus 4.5", "Open-source agent SOTA: #1 on BrowseComp, MCP-Atlas and τ²-Bench", "Real open flagship (744B MoE), self-hostable; adapted to all domestic chips", "Cheap API: GLM-5.3 at ¥8/¥28, Flash from ¥0.4/¥1.4", "Coding Plan nailed paid coding; HK-listed with ¥70B+ raised in 2026"],
      cons: ["Consumer app (Qingyan) less famous than super-apps like Doubao", "Video generation & multimodal behind ByteDance/Google", "Domestic compliance filtering applies", "Coding Plan prices rose 30%+ in Feb 2026 — watch the trend"],
      verdict: "China's top pick for programmers and heavy agent users: open, cheap, and strong. Get Coding Plan for coding.",
    },
    {
      id: "manus", name: "Manus", company: "Butterfly Effect",
      tagline: "The most autonomous general agent (storm-tested)",
      models: ["Manus 1.6 family (Lite / Standard / Max)"],
      context: "Task-dependent (multi-agent orchestration)", price: "No public free tier; from $20/mo (4,000 credits)",
      tiers: ["❌ No public free tier", "$20/mo (4,000 credits)", "$40/mo", "Top-ups"],
      china: true, chinaNote: "Available globally incl. China; HQ moved to Singapore",
      scores: { code: 4, reasoning: 4, multimodal: 4, agent: 5, chinese: 4, price: 2 },
      pros: ["The autonomy benchmark: takes a goal, plans and delivers finished work", "Once SOTA on GAIA; wide coverage (web/desktop/IM/email delegation)", "Strong end-to-end execution on open-web tasks"],
      cons: ["Meta acquisition blocked; user data wiped on re-independence — a trust disaster", "Opaque credit billing, unstable on complex tasks", "No persistent memory or team workspaces", "No free tier, $20/mo+ is pricey"],
      verdict: "Try it to taste a truly autonomous agent — but weigh the data-trust issue first. Wait and see for production.",
    },
  ],
},
ja: {
  ui: {
    doc_title: "2026年 AIエージェント徹底比較 | 主要10製品",
    meta_desc: "2026年の主要AIエージェント10製品を徹底比較。Claude、ChatGPT、Gemini、Grok、Copilot、DeepSeek、Qwen、Kimi、GLM、Manusの長所・短所・料金・選び方ガイド。",
    logo: "🤖 エージェント比較 2026",
    nav_agents: "10製品詳細", nav_compare: "比較表", nav_guide: "選び方", nav_notes: "注記",
    kicker: "2026年 · 10月更新",
    hero_a: "2026年 主要AIエージェント10選", hero_b: "徹底比較",
    hero_sub: "Claude · ChatGPT · Gemini · Grok · Copilot · DeepSeek · Qwen · Kimi · GLM · Manus<br>コーディング・推論・マルチモーダル・自律性・中国語・料金——6つの観点で一気に解説。",
    stat_n1: "10", stat_l1: "主要エージェント",
    stat_n2: "6", stat_l2: "評価観点",
    stat_n3: "4", stat_l3: "中国で利用可能な国産",
    cta: "レビューを見る ↓",
    tldr_title: "結論", tldr_tag: "TL;DR",
    tldr: [
      { t: "🏆 総合最強", p: "Claude（コード/エージェント）とGPT-6（エコシステム）がトップ tier。開発者なら間違いなし。" },
      { t: "💰 コスパ王", p: "DeepSeek：API料金は海外旗艦の1/10〜1/30、中国語推論もトップ級。" },
      { t: "🇨🇳 中国の星", p: "GLM：コーディング/エージェントでオープンソースSOTA。744Bの真のオープンな旗艦。" },
      { t: "🔓 オープンソースの頂", p: "Kimi K3：史上最大のオープンウェイト（2.8T）。Qwen：1枚のGPUで動く自前の定番。" },
    ],
    agents_title: "10製品詳細",
    agents_desc: "カードをクリックで長所・短所を展開。🇨🇳 は中国本土で直接利用可能。",
    filters: { all: "すべて", china: "🇨🇳 中国で利用可", code: "💻 コードに強い", price: "💰 コスパ良", agent: "🤖 自律性が高い" },
    compare_title: "6観点比較",
    compare_desc: "★★★★★ がトップ tier。星評価は公開ベンチマークとメディアレビューの総合判断であり、精密な測定ではない。",
    price_title: "料金プラン一覧",
    price_headers: ["製品", "無料枠", "エントリ", "主力", "最上位"],
    guide_title: "選び方ガイド",
    notes_title: "注記・出典",
    notes: [
      "本ページは2026年10月の公開情報（公式サイト・テックメディア・ベンチマーク）をもとに整理。料金・モデルは変動が激しいため、<b>購入前に必ず公式サイトで確認</b>すること。",
      "「中国語サポート」の評価は言語品質と中国本土での利用可否を総合：Claude / ChatGPT / Gemini / Grok は中国で公式サービスなし。Copilot 国際版も中国ではほぼ利用不可。",
      "注目のオープンソース・エージェントフレームワーク：<b>LangGraph</b>（ステートフルな編成、月間数千万DL）、<b>CrewAI</b>（役割分担型マルチエージェント）、<b>OpenHands</b>（自律コーディングエージェント）、各社公式SDK（Agent Framework / Agents SDK / ADK）。",
    ],
    notes_update: "最終更新：2026-10-05 · 純粋な静的ページ、バックエンドなし。出典明記で転載自由。",
    footer: "🤖 2026年 AIエージェント比較 · AIアシスタントが自動生成・デプロイ · GitHub Pages ホスティング",
    dims: { code: "コーディング", reasoning: "推論", multimodal: "マルチモーダル", agent: "エージェント自律性", chinese: "中国語サポート", price: "料金の安さ" },
    pros_label: "✅ 長所", cons_label: "❌ 短所", verdict_label: "一言評価：",
    models_label: "旗艦モデル", context_label: "コンテキスト", price_label: "料金",
    lang_label: "言語",
  },
  guides: [
    { title: "開発者 / ヘビーコーディング", body: "Claude（Codeエコシステム最強）かGPT-6 Sol。中国ならGLM（オープンソースのコーディングSOTA、Coding Planが手軽）。予算重視ならDeepSeek/KimiのAPI。" },
    { title: "中国語の執筆 / 学習 / 日常の質問（中国国内）", body: "智譜清言（GLM、無料）、Kimi（長文）、DeepSeek（深い推論）。" },
    { title: "オフィススイート", body: "企業は Microsoft 365 Copilot。中国の個人は WPS AI。" },
    { title: "自律エージェント愛好家", body: "Manus（最も自律的だが信頼性に懸念）、Claude Cowork、ChatGPT Work、またはOpenHandsの自前構築。" },
    { title: "自前構築 / プライベートデプロイ", body: "Qwen3.8-27B（1枚のGPUで動作）、DeepSeek V4.1（MIT）、Kimi K3（最強だがクラスタが必要）。" },
  ],
  agents: [
    {
      id: "claude", name: "Claude", company: "Anthropic",
      tagline: "コーディングと長期エージェントの長年の王者",
      models: ["Opus 5.5（旗艦コーディング/推論）", "Fable 5.1（最強汎用/長期エージェント）", "Sonnet 5.5（バランス型主力）"],
      context: "100万トークン", price: "Free / Pro $20/月 / Max $100–$200/月",
      tiers: ["✅（Sonnet級）", "—", "Pro $20/月", "Max $100/$200/月"],
      china: false, chinaNote: "中国で公式サービスなし",
      scores: { code: 5, reasoning: 5, multimodal: 4, agent: 5, chinese: 4, price: 3 },
      pros: ["コーディングとエージェントで長年トップ tier：Terminal-Bench 2.1で80.4%、AA知能指数58", "長文脈の理解品質が最高。大規模コードベースや長文処理に最適", "無料枠はSonnet級モデル、比較的気前が良い", "Claude Code / Cowork のエージェントエコシステムが成熟"],
      cons: ["料金が高い：Opus 5.5 APIは$4/$20、Fable 5.1は$10/$50/100万トークン", "中国本土で公式サービスなし", "中国のネットスラングや故事成語など現地文脈は国産モデルに劣る"],
      verdict: "開発者の定番。ヘビーコーディングと複雑なエージェントタスクの天井。中国の利用者はアクセス手段を各自確保する必要あり。",
    },
    {
      id: "chatgpt", name: "ChatGPT", company: "OpenAI",
      tagline: "エコシステム最充実のオールラウンダー",
      models: ["GPT-6 Astra（旗艦）", "GPT-6 Sol（中堅主力）", "GPT-6 Luna（軽量）", "GPT-6.1 Sol（強化版）"],
      context: "100万トークン", price: "Free / Go $8/月 / Plus $20/月 / Pro $200/月",
      tiers: ["✅（制限+広告あり）", "Go $8/月", "Plus $20/月", "Pro $200/月"],
      china: false, chinaNote: "中国で遮断、公式サービスなし",
      scores: { code: 5, reasoning: 5, multimodal: 4, agent: 4, chinese: 4, price: 3 },
      pros: ["総合力トップ級：GPT-6 Astraはコーディング評価で満点クラス", "最充実のエコシステム：Codex、Work、音声、Deep Research", "明確な料金体系。Plus $20/月でSol級が使える"],
      cons: ["旗艦は高い：Astra API $10/$50、Proプラン$200/月", "無料枠は広告付きで制限が厳しい。Sora単体アプリは終了", "中国語は翻訳調になりがち。古文やネットミームは国産に劣る", "中国本土で公式サービスなし"],
      verdict: "万能の優等生、エコシステムと使いやすさは随一。極限のコーディングならSol、日常はPlusで十分。",
    },
    {
      id: "gemini", name: "Gemini", company: "Google",
      tagline: "マルチモーダルと音声のコスパ王",
      models: ["Gemini 3.8 Flash（開発者主力）", "Gemini 3.8 Live（リアルタイム音声エージェント）", "Gemini 3.1 Pro（コンシューマ旗艦）"],
      context: "100万+トークン", price: "Free（10/9以降はFlash-Liteのみ）/ Plus $4.99/月 / Pro $19.99/月 / Ultra $99.99+/月",
      tiers: ["✅（10/9以降はFlash-Liteのみ）", "Plus $4.99/月", "Pro $19.99/月", "Ultra $99.99/$199.99/月"],
      china: false, chinaNote: "中国で遮断、公式サービスなし",
      scores: { code: 4, reasoning: 4, multimodal: 5, agent: 4, chinese: 4, price: 4 },
      pros: ["最強のネイティブマルチモーダル：テキスト/画像/動画/音声/PDF", "リアルタイム音声が業界トップ、97言語対応", "Flashは安くて速い。Googleエコシステム（検索/Android/Workspace）と最深統合"],
      cons: ["2026-10-09以降、無料枠が大幅縮小（Flash-Liteのみ）", "旗艦の命名が混乱、コンシューマの tier 対応が不透明", "独立ベンチマークではClaude/GPT-6旗艦にやや劣る", "中国本土で公式サービスなし"],
      verdict: "マルチモーダルと音声用途の第一選択。Android/Googleユーザーは即決。無料利用者は10月以降の縮小に注意。",
    },
    {
      id: "grok", name: "Grok", company: "xAI",
      tagline: "リアルタイム情報の反逆者",
      models: ["Grok 4.7（旗艦）", "Grok 4.7 Fast（2倍速）"],
      context: "50万トークン", price: "無料ベーシック / X Premium $8–$40 / SuperGrok $10–$300/月",
      tiers: ["✅ ベーシック", "X Premium $8 / Lite $10", "SuperGrok $30 / Premium+ $40", "Plus $100 / Heavy $300"],
      china: false, chinaNote: "中国で利用不可（Xが遮断）",
      scores: { code: 4, reasoning: 4, multimodal: 4, agent: 3, chinese: 3, price: 4 },
      pros: ["Xのリアルタイム検索で鮮度は随一", "Grok Imagineの動画/画像生成（1080p）", "APIが安い（$2/$6）、企業導入が速い", "物怖じしない語調で若年層に人気"],
      cons: ["性能はまだトップ tier に一歩及ばず。自称ベンチマークと第三者の乖離あり", "料金体系が混乱：X PremiumとSuperGrokの二重運営、モデル対応が不透明", "中国語品質は国産モデルに明確に劣る", "中国本土で利用不可"],
      verdict: "リアルタイムの話題追跡や動画生成なら試す価値あり。本格的な生産性用途は上位3社から。",
    },
    {
      id: "copilot", name: "Microsoft Copilot", company: "マイクロソフト",
      tagline: "オフィス業務のデフォルト回答",
      models: ["内部はOpenAI AstraとAnthropic Fableの混合", "Home / Code / Autopilot の3タブ（2026年9月刷新）"],
      context: "基盤モデルに依存", price: "ベーシック無料 / M365 Business $21/月 / Enterprise $30/ユーザー/月+従量",
      tiers: ["✅（Win/Edgeベーシック）", "—", "M365 Business $21/月", "Enterprise $30/月+従量"],
      china: false, chinaNote: "国際版は中国でほぼ利用不可",
      scores: { code: 4, reasoning: 4, multimodal: 3, agent: 4, chinese: 3, price: 2 },
      pros: ["M365との最深統合：Word/Excel/PPTをその場で生成・編集", "Autopilot：バックグラウンドで動き続ける自律エージェント", "Windows/Edgeにプリインストール、到達範囲は最大"],
      cons: ["サブスク+従量の二重課金。エージェントの高負荷は別料金で請求が読めない", "自社旗艦基盤モデルなし。最先端モデルの搭載はネイティブアプリより遅い", "中国語の語感や現地化は国産アシスタントに劣る"],
      verdict: "企業のオフィス業務には必須。個人はOffice統合への対価。高負荷エージェント利用前に料金試算を。",
    },
    {
      id: "deepseek", name: "DeepSeek", company: "深度求索",
      tagline: "コスパ王、オープン推論の星",
      models: ["DeepSeek V4.1 Flash（ネイティブマルチモーダルMoE、MITオープン）", "DeepSeek V4 Pro（1.6T、ウェイト公開）"],
      context: "100万トークン", price: "アプリ/Web無料。APIは約¥2/¥8/100万トークン（閑散期は半額）",
      tiers: ["✅", "—", "激安API（¥2/¥8）", "—"],
      china: true, chinaNote: "中国で完全利用可",
      scores: { code: 5, reasoning: 5, multimodal: 3, agent: 4, chinese: 5, price: 5 },
      pros: ["圧倒的コスパ：海外旗艦の1/10〜1/30、キャッシュヒットはほぼ無料", "MITオープンのウェイト、自前デプロイ可", "中国語の推論・執筆・コードコメントはトップ tier", "国産チップへのゼロデイ対応、エコシステムの反応が速い"],
      cons: ["ピーク時の安定性に波あり", "動画生成などマルチモーダルはByteDance/Googleに劣る", "センシティブな話題はコンプライアンス審査あり", "コンシューマアプリの作り込みは大手に劣る"],
      verdict: "開発者と予算重視派のデフォルト選択。APIの安さは無敵、日常の質問は無料枠で十分。",
    },
    {
      id: "qwen", name: "Qwen", company: "アリババ",
      tagline: "オープンエコシステムの絶対王者",
      models: ["Qwen3.8-Max（クローズド旗艦、中国最強）", "Qwen3.8-2.4T-A95B（オープンMoE）", "Qwen3.8-27B（Apache 2.0、1枚のGPUで動作）"],
      context: "100万トークン（27BはYaRNで拡張）", price: "オープンウェイト無料。通義アプリ無料。従量APIも安い",
      tiers: ["✅", "—", "安いAPI", "—"],
      china: true, chinaNote: "中国で完全利用可",
      scores: { code: 4, reasoning: 4, multimodal: 4, agent: 4, chinese: 5, price: 5 },
      pros: ["最強のオープンエコシステム：460+モデル、30億+DL、30万+派生", "27B Apache 2.0はRTX 4090 1枚で動作。自前導入のハードル最低", "中国語トップ級、Alibaba Cloud/Alipayとの深い統合", "中国版Apple Intelligenceへの採用の噂"],
      cons: ["最強のMax版はクローズド。2.4T版は大規模商用にライセンス要", "独立した第三者評価はDeepSeekより薄い", "国際的な開発者支持はまだ追走中"],
      verdict: "ローカル/自前デプロイなら即決Qwen。オープンなエージェント基盤の事実上の標準。",
    },
    {
      id: "kimi", name: "Kimi", company: "Moonshot AI",
      tagline: "最強のオープンモデル、長文の王",
      models: ["Kimi K3（2.8T MoE、史上最大のオープンウェイト）", "Kimi K2.8 Preview（中堅）"],
      context: "100万トークン（全 tier）", price: "アプリ/Web無料。K3 APIは約$3/$15/100万トークン",
      tiers: ["✅", "—", "API $3/$15（K3）", "—"],
      china: true, chinaNote: "中国で完全利用可",
      scores: { code: 5, reasoning: 5, multimodal: 3, agent: 4, chinese: 5, price: 4 },
      pros: ["AA知能指数57.1、最強のオープンモデル（世界4位）", "フロントエンドのコーディングでClaude/GPTを初めて超えたオープンなモデル", "長文脈とエージェントの評判良し。Kimi Codeターミナルエージェントが便利", "中国語タスクが優秀、中国で完全利用可"],
      cons: ["ウェイト1.56TB、個人でのローカル実行は不可", "独自ライセンス、商用は条項要確認", "動画/音声生成はByteDanceに劣る", "BATより小規模、長期投資は様子見"],
      verdict: "長文処理とオープンなエージェントの第一選択。論文・コードベース・針の穴探しはKimiへ。",
    },
    {
      id: "glm", name: "GLM", company: "智譜AI",
      tagline: "コーディング/エージェント両部門のオープンSOTA",
      models: ["GLM-5（旗艦、744Bオープン）", "GLM-5.3（最新、1Mコンテキスト）", "GLM-5.3-Flash（高速・格安版）"],
      context: "100万トークン（GLM-5.3）", price: "智譜清言は無料。API ¥8/¥28（5.3）。Coding Planは¥118〜",
      tiers: ["✅（智譜清言）", "Coding Plan ¥118", "API ¥8/¥28（5.3）", "Flash ¥0.4/¥1.4"],
      china: true, chinaNote: "中国で完全利用可",
      scores: { code: 5, reasoning: 5, multimodal: 4, agent: 5, chinese: 5, price: 5 },
      pros: ["コーディングでオープンSOTA：SWE-bench-Verified 77.8、Terminal-Bench 2.0で56.2。Claude Opus 4.5に迫る体感", "エージェントもオープンSOTA：BrowseComp、MCP-Atlas、τ²-Benchでオープン1位", "真のオープン旗艦（744B MoE）、自前デプロイ可。国産チップに完全対応", "APIが安い：GLM-5.3は¥8/¥28、Flashは¥0.4/¥1.4〜", "GLM Coding Planで有料コーディングを確立。2026年香港上場で700億HK$超を調達"],
      cons: ["コンシューマアプリ（智譜清言）の知名度はDoubao級に及ばず", "動画生成などマルチモーダルはByteDance/Googleに劣る", "国内コンプライアンス審査あり", "2026年2月にCoding Planが30%〜値上げ。値上げ傾向に注意"],
      verdict: "開発者とヘビーなエージェント利用者の中国における第一選択。オープン・安い・強い。コードを書くならCoding Planへ。",
    },
    {
      id: "manus", name: "Manus", company: "Butterfly Effect",
      tagline: "最も自律的な汎用エージェント（荒波を越えて）",
      models: ["Manus 1.6ファミリー（Lite / Standard / Max）"],
      context: "タスク依存（マルチエージェント編成）", price: "公開の無料枠なし。$20/月（4,000クレジット）〜",
      tiers: ["❌ 公開の無料枠なし", "$20/月（4,000クレジット）", "$40/月", "追加購入"],
      china: true, chinaNote: "中国含め世界で利用可。本社はシンガポールへ",
      scores: { code: 4, reasoning: 4, multimodal: 4, agent: 5, chinese: 4, price: 2 },
      pros: ["自律性のベンチマーク：目標を与えれば自律計画・実行して成果物を納品", "GAIAで一時SOTA。Web/デスクトップ/IM/メール委任と多端対応", "オープンなネットタスクのエンドツーエンド実行に強い"],
      cons: ["Meta買収が頓挫、独立回復時にユーザーデータを削除——信頼の災難", "クレジット課金が不透明、複雑タスクの失敗率が不安定", "永続メモリやチーム協業スペースなし", "無料枠なし、$20/月〜は高め"],
      verdict: "真の自律エージェントを味わうなら一見の価値あり。ただしデータ信頼の問題を先に検討。本番利用は様子見推奨。",
    },
  ],
},
};
