/* 2026 年主流 AI Agent 横评数据（调研日期：2026-10-05，源自公开资料整理） */
const AGENTS = [
  {
    id: "claude",
    name: "Claude",
    company: "Anthropic",
    tagline: "代码与长任务 Agent 的长期王者",
    models: ["Opus 5.5（旗舰编码/推理）", "Fable 5.1（最强通用/长时 Agent）", "Sonnet 5.5（均衡主力）"],
    context: "100 万 tokens",
    price: "Free / Pro $20/月 / Max $100–$200/月",
    china: false,
    chinaNote: "大陆无官方服务",
    scores: { code: 5, reasoning: 5, multimodal: 4, agent: 5, chinese: 4, price: 3 },
    pros: [
      "代码与 Agent 任务长期第一梯队：Terminal-Bench 2.1 达 80.4%，AA 智能指数 58 领先",
      "长上下文理解质量最好，适合大代码库与长文档",
      "免费档默认给 Sonnet 级别模型，免费层相对慷慨",
      "Claude Code / Cowork 终端与办公 Agent 生态成熟",
    ],
    cons: [
      "定价贵：Opus 5.5 API $4/$20，Fable 5.1 高达 $10/$50 每百万 token",
      "中国大陆无官方服务",
      "中文网络语境、成语典故等本地化知识弱于国产模型",
    ],
    verdict: "程序员首选，重度编码与复杂 Agent 任务的天花板；国内用户需自行解决访问问题。",
  },
  {
    id: "chatgpt",
    name: "ChatGPT",
    company: "OpenAI",
    tagline: "生态最完整的全能选手",
    models: ["GPT-6 Astra（旗舰）", "GPT-6 Sol（中端主力）", "GPT-6 Luna（轻量）", "GPT-6.1 Sol（升级版）"],
    context: "100 万 tokens",
    price: "Free / Go $8/月 / Plus $20/月 / Pro $200/月",
    china: false,
    chinaNote: "大陆被屏蔽，无官方服务",
    scores: { code: 5, reasoning: 5, multimodal: 4, agent: 4, chinese: 4, price: 3 },
    pros: [
      "综合实力最强之一：GPT-6 Astra 编码实测满分档",
      "生态最完整：Codex 编程 Agent、Work 文档生成、语音、Deep Research",
      "分层定价清晰，Plus $20/月可用 Sol 级别",
    ],
    cons: [
      "旗舰贵：Astra API $10/$50，Pro 档 $200/月",
      "免费档含广告且限制严格；Sora 独立应用已下线",
      "中文表达偏翻译腔，古文与网络热梗理解不如国产",
      "中国大陆无官方服务",
    ],
    verdict: "全能水桶机，生态与易用性最佳；追求极致编码可选 Sol，日常用 Plus 足够。",
  },
  {
    id: "gemini",
    name: "Gemini",
    company: "Google",
    tagline: "多模态与语音的性价比之王",
    models: ["Gemini 3.8 Flash（开发者主力）", "Gemini 3.8 Live（实时语音 Agent）", "Gemini 3.1 Pro（消费旗舰）"],
    context: "100 万+ tokens",
    price: "Free（10/9 后仅 Flash-Lite）/ Plus $4.99/月 / Pro $19.99/月 / Ultra $99.99+/月",
    china: false,
    chinaNote: "大陆被屏蔽，无官方服务",
    scores: { code: 4, reasoning: 4, multimodal: 5, agent: 4, chinese: 4, price: 4 },
    pros: [
      "原生多模态最强：文本/图像/视频/音频/PDF 全支持",
      "语音实时对话领先，支持 97 种语言",
      "Flash 系列便宜又快，谷歌生态（搜索/安卓/Workspace）整合最深",
    ],
    cons: [
      "2026-10-09 起免费档大幅缩水，只剩 Flash-Lite",
      "旗舰命名混乱，消费端档位对应不透明",
      "独立基准整体略逊 Claude/GPT-6 旗舰",
      "中国大陆无官方服务",
    ],
    verdict: "多模态与语音场景首选，安卓/谷歌全家桶用户闭眼入；免费党注意 10 月后的缩水。",
  },
  {
    id: "grok",
    name: "Grok",
    company: "xAI",
    tagline: "实时信息流的叛逆者",
    models: ["Grok 4.7（旗舰）", "Grok 4.7 Fast（2 倍速）"],
    context: "50 万 tokens",
    price: "免费基础版 / X Premium $8–$40 / SuperGrok $10–$300/月",
    china: false,
    chinaNote: "大陆不可用（X 被屏蔽）",
    scores: { code: 4, reasoning: 4, multimodal: 4, agent: 3, chinese: 3, price: 4 },
    pros: [
      "X 平台实时信息搜索，时效性最强",
      "Grok Imagine 视频/图像生成（1080p）",
      "API 便宜（$2/$6），企业落地快",
      "调性敢说，吸引年轻用户",
    ],
    cons: [
      "性能仍落后第一梯队一个身位，自报基准与第三方有差距",
      "订阅体系混乱：X Premium 与 SuperGrok 双店并行，模型映射不透明",
      "中文质量明显弱于国产模型",
      "中国大陆不可用",
    ],
    verdict: "追实时热点、玩视频生成可以一试；严肃生产力任务先看前三家。",
  },
  {
    id: "copilot",
    name: "Microsoft Copilot",
    company: "微软",
    tagline: "办公场景的默认答案",
    models: ["底层混用 OpenAI Astra 与 Anthropic Fable", "Home / Code / Autopilot 三标签（2026-09 改版）"],
    context: "依底层模型而定",
    price: "基础免费 / M365 商业版 $21/月 / 企业版 $30/用户/月 + 按量",
    china: false,
    chinaNote: "国际版大陆基本不可用",
    scores: { code: 4, reasoning: 4, multimodal: 3, agent: 4, chinese: 3, price: 2 },
    pros: [
      "M365 全家桶深度集成：Word/Excel/PPT 内直接生成编辑",
      "Autopilot 后台持续运行的自主 Agent",
      "Windows/Edge 预装，触达最广",
    ],
    cons: [
      "订阅 + 按量双重计费，Agent 重负载另收费，账单不可预测",
      "无自研旗舰基座模型，前沿模型上线慢于原生应用",
      "中文语感与知识本地化弱于国产助手",
    ],
    verdict: "企业办公刚需，个人用户为 Office 整合买单；重度 Agent 用量前先算好账。",
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    company: "深度求索",
    tagline: "性价比之王，开源推理之光",
    models: ["DeepSeek V4.1 Flash（原生多模态 MoE，MIT 开源）", "DeepSeek V4 Pro（1.6T，权重开源）"],
    context: "100 万 tokens",
    price: "App/网页免费；API 约 ¥2/¥8 每百万 token（闲时半价）",
    china: true,
    chinaNote: "大陆完全可用",
    scores: { code: 5, reasoning: 5, multimodal: 3, agent: 4, chinese: 5, price: 5 },
    pros: [
      "性价比之王：API 价格是国外旗舰的 1/10–1/30，缓存命中近乎免费",
      "MIT 开源权重，可私有化部署",
      "中文推理/写作/代码注释均为第一梯队",
      "首发即获国产芯片零日适配，生态响应快",
    ],
    cons: [
      "高峰期服务稳定性偶有波动",
      "视频生成等多模态弱于字节/谷歌",
      "敏感话题受合规审查",
      "消费端 App 功能不如豆包丰富",
    ],
    verdict: "开发者与预算敏感用户的默认选择；API 性价比无敌，日常问答免费够用。",
  },
  {
    id: "qwen",
    name: "Qwen",
    company: "阿里",
    tagline: "开源生态的绝对王者",
    models: ["Qwen3.8-Max（闭源旗舰，国产第一）", "Qwen3.8-2.4T-A95B（开源 MoE）", "Qwen3.8-27B（Apache 2.0，单卡可跑）"],
    context: "100 万 tokens（27B 经 YaRN 扩展）",
    price: "开源权重免费；通义 App 免费；API 按量便宜",
    china: true,
    chinaNote: "大陆完全可用",
    scores: { code: 4, reasoning: 4, multimodal: 4, agent: 4, chinese: 5, price: 5 },
    pros: [
      "开源生态最强：460+ 模型、30 亿+ 下载、30 万+ 衍生",
      "27B Apache 2.0 单张 RTX 4090 可跑，私有化门槛最低",
      "中文能力顶级，阿里云/支付宝生态整合深",
      "有望接入国行 Apple Intelligence",
    ],
    cons: [
      "最强 Max 版闭源，2.4T 版超大规模商用需授权",
      "独立第三方评测证据弱于 DeepSeek",
      "国际开发者生态仍在追赶",
    ],
    verdict: "想本地跑/私有化部署闭眼选 Qwen；开源 Agent 底座的事实标准。",
  },
  {
    id: "kimi",
    name: "Kimi",
    company: "月之暗面",
    tagline: "最强开源模型，长文档之王",
    models: ["Kimi K3（2.8T MoE，史上最大开源权重）", "Kimi K2.8 Preview（中端）"],
    context: "100 万 tokens（全档）",
    price: "App/网页免费；API K3 约 $3/$15 每百万 token",
    china: true,
    chinaNote: "大陆完全可用",
    scores: { code: 5, reasoning: 5, multimodal: 3, agent: 4, chinese: 5, price: 4 },
    pros: [
      "AA 智能指数 57.1，最强开源模型（全球第四）",
      "首个前端编码基准超越 Claude/GPT 的开源模型",
      "长上下文与 Agent 任务口碑好，Kimi Code 终端 Agent 好用",
      "中文任务优秀，大陆完全可用",
    ],
    cons: [
      "权重 1.56TB，个人无法本地运行",
      "自研 License，商用需细读条款",
      "视频/语音等多模态生成弱于字节",
      "公司体量小于 BAT，长期投入待观察",
    ],
    verdict: "长文档处理与开源 Agent 首选；读论文、啃代码库、大海捞针找它。",
  },
  {
    id: "doubao",
    name: "豆包",
    company: "字节跳动",
    tagline: "3.4 亿月活的国民 AI",
    models: ["Doubao-Seed-2.1 Pro", "Seedance 2.5（视频生成）", "SeedRealtime（实时音视频通话）"],
    context: "长上下文（依版本而定）",
    price: "App 基础免费；付费版 ¥68/¥200/¥500/月",
    china: true,
    chinaNote: "大陆完全可用",
    scores: { code: 4, reasoning: 4, multimodal: 5, agent: 4, chinese: 5, price: 4 },
    pros: [
      "MAU 3.45 亿、DAU 1.4 亿，断层第一的国民级 App",
      "中文写作/PPT/视频生成/实时语音通话本土体验最强",
      "字节生态整合：抖音/飞书/火山引擎/车载",
      "免费档功能慷慨，日常全覆盖",
    ],
    cons: [
      "2026 年推付费档引发争议，免费档未来可能缩水",
      "App 内自建智能体因新规下线",
      "内容受国内合规审查",
      "国际版影响力小",
    ],
    verdict: "国内普通用户的无脑首选：免费、好用、中文最强；视频与实时通话独一档。",
  },
  {
    id: "manus",
    name: "Manus",
    company: "Butterfly Effect",
    tagline: "最自主的通用 Agent（历经风波）",
    models: ["Manus 1.6 家族（Lite / Standard / Max）"],
    context: "依任务而定（多 Agent 编排）",
    price: "无公开免费档；$20/月（4000 点）起",
    china: true,
    chinaNote: "全球可用（含中国访问），主体已迁新加坡",
    scores: { code: 4, reasoning: 4, multimodal: 4, agent: 5, chinese: 4, price: 2 },
    pros: [
      "Agent 自主性标杆：给目标就自主规划执行，交付成品",
      "GAIA 基准曾达 SOTA，多端覆盖（Web/桌面/IM/邮件委托）",
      "开放网络任务的端到端执行能力强",
    ],
    cons: [
      "Meta 收购被叫停、恢复独立时删除用户数据，信任受重创",
      "信用点计费不透明，复杂任务失败率不稳定",
      "无持久记忆与团队协作空间",
      "无免费档，$20/月起偏贵",
    ],
    verdict: "想体验'真·自主 Agent'可以一试，但先想清楚数据信任问题；生产环境建议观望。",
  },
];

const GUIDES = [
  { title: "程序员 / 重度编码", body: "Claude（Code 生态最强）或 GPT-6 Sol（性价比）；预算敏感直接上 DeepSeek / Kimi API。" },
  { title: "中文写作 / 学习 / 日常问答（国内）", body: "豆包（功能最全、免费）、Kimi（长文档）、DeepSeek（深度推理）。" },
  { title: "办公全家桶", body: "企业看 Microsoft 365 Copilot；国内个人看豆包专业版。" },
  { title: "自主 Agent 玩家", body: "Manus（最自主但有信任风险）、Claude Cowork、ChatGPT Work，或用 OpenHands 自建。" },
  { title: "开发者自建 / 私有化", body: "Qwen3.8-27B（单卡可跑）、DeepSeek V4.1（MIT）、Kimi K3（最强但需集群）。" },
];

const DIM_LABELS = { code: "代码能力", reasoning: "推理", multimodal: "多模态", agent: "Agent 自主性", chinese: "中文支持", price: "价格亲和" };
